# Generated by Django 6.0.3 on 2026-03-31 16:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_alter_pelicula_anio'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='dni',
            field=models.CharField(default='00000000', max_length=8, unique=True, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='DNI'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pelicula',
            name='stock',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
