# Generated by Django 6.0.3 on 2026-03-31 16:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_cliente_dni_pelicula_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='duracion_minutos',
            field=models.PositiveIntegerField(default=90, help_text='Duración en minutos.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Duración (minutos)'),
        ),
    ]
