# Generated by Django 6.0.3 on 2026-04-01 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_pelicula_duracion_minutos'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttemptAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('path', models.CharField(blank=True, max_length=200, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'Intento de login fallido',
                'verbose_name_plural': 'Intentos de login fallidos',
                'ordering': ['-attempted_at'],
            },
        ),
    ]
