# Generated by Django 6.0.3 on 2026-04-01 17:14

from django.db import migrations, models
from django.utils.text import slugify


def populate_estado_and_slug(apps, schema_editor):
    Pelicula = apps.get_model("tienda", "Pelicula")
    Alquiler = apps.get_model("tienda", "Alquiler")

    for pelicula in Pelicula.objects.all().order_by("id"):
        if pelicula.slug:
            continue

        base_slug = slugify(pelicula.titulo)[:220] or "pelicula"
        candidate = base_slug
        counter = 2
        while Pelicula.objects.filter(slug=candidate).exclude(pk=pelicula.pk).exists():
            suffix = f"-{counter}"
            candidate = f"{base_slug[: 240 - len(suffix)]}{suffix}"
            counter += 1
        pelicula.slug = candidate
        pelicula.save(update_fields=["slug"])

    Alquiler.objects.filter(pagado=True).update(estado="pagado")
    Alquiler.objects.filter(pagado=False).update(estado="pendiente")


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_loginattemptaudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='alquiler',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('anulado', 'Anulado')], default='pendiente', max_length=10),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='slug',
            field=models.SlugField(blank=True, max_length=240, null=True, unique=True),
        ),
        migrations.RunPython(populate_estado_and_slug, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='pelicula',
            name='slug',
            field=models.SlugField(max_length=240, unique=True),
        ),
    ]
