# Generated by Django 6.0.3 on 2026-04-01 20:27

import django.db.models.deletion
from django.db import migrations, models


def backfill_fecha_pago(apps, schema_editor):
    Alquiler = apps.get_model("tienda", "Alquiler")
    for alquiler in Alquiler.objects.filter(pagado=True, fecha_pago__isnull=True):
        alquiler.fecha_pago = alquiler.fecha_devolucion or alquiler.fecha_alquiler
        alquiler.save(update_fields=["fecha_pago"])


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_alquiler_estado_pelicula_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Método de pago',
                'verbose_name_plural': 'Métodos de pago',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='alquiler',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='metodo_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alquileres', to='tienda.metodopago'),
        ),
        migrations.RunPython(backfill_fecha_pago, migrations.RunPython.noop),
    ]
