# Generated by Django 6.0.3 on 2026-04-01 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_metodopago_alquiler_fecha_pago_alquiler_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='director',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='pais_origen',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
