# Generated by Django 6.0.3 on 2026-04-01 21:21

from datetime import timedelta

from django.db import migrations, models


def deduplicate_alquileres_por_cliente_pelicula_fecha(apps, schema_editor):
    Alquiler = apps.get_model("tienda", "Alquiler")
    seen = set()

    alquileres = Alquiler.objects.all().order_by("cliente_id", "pelicula_id", "fecha_alquiler", "id")
    for alquiler in alquileres:
        original_fecha = alquiler.fecha_alquiler
        nueva_fecha = original_fecha
        key = (alquiler.cliente_id, alquiler.pelicula_id, nueva_fecha)

        while key in seen:
            nueva_fecha = nueva_fecha + timedelta(days=1)
            key = (alquiler.cliente_id, alquiler.pelicula_id, nueva_fecha)

        if nueva_fecha != original_fecha:
            updates = {"fecha_alquiler": nueva_fecha}
            if alquiler.fecha_devolucion and alquiler.fecha_devolucion < nueva_fecha:
                updates["fecha_devolucion"] = nueva_fecha
            if alquiler.fecha_pago and alquiler.fecha_pago < nueva_fecha:
                updates["fecha_pago"] = nueva_fecha
            Alquiler.objects.filter(pk=alquiler.pk).update(**updates)

        seen.add(key)


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0008_pelicula_director_pelicula_pais_origen'),
    ]

    operations = [
        migrations.RunPython(deduplicate_alquileres_por_cliente_pelicula_fecha, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='alquiler',
            constraint=models.UniqueConstraint(fields=('cliente', 'pelicula', 'fecha_alquiler'), name='uq_alquiler_cliente_pelicula_fecha'),
        ),
    ]
