# Generated by Django 6.0.3 on 2026-04-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0009_alquiler_uq_alquiler_cliente_pelicula_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='CajaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('cerrada_en', models.DateTimeField(auto_now_add=True)),
                ('cerrada_por', models.CharField(blank=True, default='', max_length=150)),
            ],
            options={
                'verbose_name': 'Caja diaria',
                'verbose_name_plural': 'Cajas diarias',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='categoria',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='metodopago',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
