# Generated by Django 6.0.3 on 2026-04-02 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0010_cajadiaria_categoria_is_active_cliente_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=80)),
                ('entidad', models.CharField(max_length=80)),
                ('objeto_id', models.PositiveIntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, default='', max_length=255)),
                ('username', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Auditoría de acción',
                'verbose_name_plural': 'Auditoría de acciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
