# Generated by Django 6.0.3 on 2026-04-03 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0012_usersecurityprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoDominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(max_length=80)),
                ('entidad', models.CharField(max_length=80)),
                ('referencia_id', models.PositiveIntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, default='', max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Evento de dominio',
                'verbose_name_plural': 'Eventos de dominio',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistorialPrecioPelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_anterior', models.DecimalField(decimal_places=2, max_digits=8)),
                ('precio_nuevo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_precios', to='tienda.pelicula')),
            ],
            options={
                'verbose_name': 'Historial de precio de película',
                'verbose_name_plural': 'Historial de precios de películas',
                'ordering': ['-changed_at'],
            },
        ),
    ]
